### ISSUE TITLE
♻️ Smart contracts best practices for optional values with defaults

### ISSUE THREAD

**Issue by ccamel** [okp4/contracts#185]
## Issue

There are some inconsistencies in the way we handle optional values and defaults in our smart contracts, especially with regard to messages and state.

## Idea

As we are currently experiencing variations in the principles applied, I propose the following rule to address the matter. This is something that is open to discussion of course.

**Messages**

Regarding `messages`, in the definition of `instantiate` and `execute` messages, optional values can be considered, with explicit default values in the comments. In the implementation, methods should be included to should to retrieve values or default values - for instance like `max_page_size_or_default`  for `max_page_size` property.

For message `responses`, types with default values should not have optional values. So when a type has a default value, the response should always include the value or the default value if none. It will avoid the need for clients to explicitly handle optional values, and help them handle default values.

**State**

On the `state` side, I believe that default values should be used whenever possible, which eliminates any use of the optional type.

## Todo

- [ ] reach a consensus on this matter
- [ ] implement the proposed change

**Comment by bdeneux** [comment]
@ccamel I'm completely agree to limit usage of `Optional` at the `state` side, another solution at the `message` side is to use the [`serde` attribute to set a default value on each field](https://serde.rs/attr-default.html). In addition to the `state` side optional removing, it's allow us to remove all optionals, on the `message` and `state` side. 

```rust
/// # StoreLimitsInput
/// Contains requested limitations regarding store usages.
#[cw_serde]
#[derive(Default, Builder)]
#[builder(default, setter(into, strip_option))]
pub struct StoreLimitsInput {
    /// The maximum number of triples the store can contains.
    /// If `None`, the default value of [Uint128::MAX] is used, which can be considered as no limit.
    #[serde(default = "Uint128::MAX")] 
    pub max_triple_count: Uint128,
}
```

The cons of this solution is that when we are looking API, we didn't see at the first time that those field are optional and can be omitted when instantiate contract. I don't think that the generated documentation will handle this attribute and indicate that a field is 

In any case, we could start removing the optional on the state part.

**Comment by bdeneux** [comment]
**Progress:**  

- [ ] okp4-objectarium: 🚧 #223 
- [ ] okp4-cognitarium: ❌ 
- [x] okp4-law-stone: N/A
