### ISSUE TITLE
💿 🔄 Objectarium : support for Object Compression

### ISSUE THREAD

**Issue by ccamel** [okp4/contracts#192]
##  Idea

The `objectarium` smart contract enables object storage on-chain. However, as the size of objects stored on-chain increases, so does the gas cost required to store them.

One way to address this issue is by adding support for compression. This would allow users to compress their data before storing it on-chain, potentially reducing the amount of gas required to store the object. Users could make a trade-off between the gas cost required for storage (due to the size of the object) and the gas cost required for computation (due to compression).

To gain a deeper understanding of how the smart contract behaves with compression in terms of gas consumption, benchmarking could be a useful approach (cf. #191).

## Todo

- [ ] Evaluate the relevance of the proposal.
- [ ] Research and select one or two CPU-efficient compression algorithms.
- [ ] Design the contract interface to accommodate compression.
- [ ] Implement.
- [ ] Test.
- [ ] Document the feature. Would be nice to consider the impact of compression on gas consumption and document any potential trade-offs.

**Comment by ChaimaaZaoui** [comment]
@ccamel any progress about this ticket ?

**Comment by ccamel** [comment]
@ChaimaaZaoui it's currently in progress. Not of essential value but will allow to start addressing from different angles the aspects of gas fees related to storage or CPU consumption.
